/**
 * Remote benchmark Worker.
 * Deployed nightly to measure parser performance in the real Cloudflare runtime.
 *
 * GET /bench?fixture=<name>&iterations=<n>&warmup=<n>
 * GET /health
 * GET /fixtures
 */
import { parse } from "./index.js";

// Fixtures are inlined at build time via `?raw` imports so the deployed
// Worker is self-contained (no KV/R2 needed for the default suite).
// Large fixtures are generated by `npm run fixtures:generate`.
import attrsHeavy from "../test/fixtures/generated/attrs-heavy-100k.xml?raw";
import cdataHeavy from "../test/fixtures/generated/cdata-heavy-100k.xml?raw";
import deepNesting from "../test/fixtures/generated/deep-nesting-100k.xml?raw";
import large1mb from "../test/fixtures/generated/large-1mb.xml?raw";
import rss100k from "../test/fixtures/generated/rss-100k.xml?raw";
import tiny1k from "../test/fixtures/generated/tiny-1k.xml?raw";

const FIXTURES: Record<string, string> = {
  "tiny-1k": tiny1k,
  "rss-100k": rss100k,
  "attrs-heavy-100k": attrsHeavy,
  "deep-nesting-100k": deepNesting,
  "cdata-heavy-100k": cdataHeavy,
  "large-1mb": large1mb,
};

function quantile(sorted: number[], q: number): number {
  if (sorted.length === 0) return 0;
  const index = Math.min(sorted.length - 1, Math.ceil(q * sorted.length) - 1);
  return sorted[index] ?? 0;
}

function mean(values: number[]): number {
  if (values.length === 0) return 0;
  return values.reduce((a, b) => a + b, 0) / values.length;
}

export default {
  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/health") {
      return Response.json({ ok: true, version: "remote-bench-v1" });
    }

    if (url.pathname === "/fixtures") {
      const list = Object.fromEntries(Object.entries(FIXTURES).map(([k, v]) => [k, v.length]));
      return Response.json({ fixtures: list });
    }

    if (url.pathname === "/bench") {
      const fixtureName = url.searchParams.get("fixture") ?? "rss-100k";
      const iterations = Math.min(
        Math.max(Number(url.searchParams.get("iterations") ?? "50"), 1),
        500,
      );
      const warmup = Math.min(Math.max(Number(url.searchParams.get("warmup") ?? "5"), 0), 50);
      const xml = FIXTURES[fixtureName];
      if (xml === undefined) {
        return Response.json({ error: `unknown fixture: ${fixtureName}` }, { status: 400 });
      }

      for (let i = 0; i < warmup; i++) {
        try {
          parse(xml);
        } catch {
          // Placeholder parser throws; timing harness still works once implemented.
          break;
        }
      }

      const samples: number[] = [];
      for (let i = 0; i < iterations; i++) {
        const start = performance.now();
        try {
          parse(xml);
        } catch {
          // Until the parser is implemented, record the overhead only.
        }
        samples.push(performance.now() - start);
      }
      samples.sort((a, b) => a - b);
      const bytes = xml.length;
      const medianMs = quantile(samples, 0.5);
      const mbPerSec = medianMs > 0 ? bytes / 1024 / 1024 / (medianMs / 1000) : 0;

      return Response.json({
        fixture: fixtureName,
        bytes,
        iterations,
        warmup,
        avgMs: mean(samples),
        medianMs,
        p95Ms: quantile(samples, 0.95),
        p99Ms: quantile(samples, 0.99),
        minMs: samples[0] ?? 0,
        maxMs: samples[samples.length - 1] ?? 0,
        mbPerSec,
        timestamp: new Date().toISOString(),
      });
    }

    return Response.json({ error: "not found" }, { status: 404 });
  },
};
