/**
 * Synthetic XML fixtures shared by the local generator (scripts/generate-fixtures.mjs)
 * and the remote bench Worker, so a fixture name means the same document everywhere.
 * Erasable TypeScript only: Node runs this file directly via type stripping.
 */

function rssFeed(items: number, textLength: number): string {
  const lorem = "Lorem ipsum dolor sit amet "
    .repeat(Math.ceil(textLength / 27))
    .slice(0, textLength);
  let out = `<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0"><channel><title>Bench</title>`;
  for (let index = 0; index < items; index++) {
    out += `<item id="${index}"><title>Item ${index}</title><link>https://example.com/${index}</link><description>${lorem}</description><pubDate>Mon, 01 Jan 2024 00:00:00 GMT</pubDate></item>`;
  }
  return out + `</channel></rss>`;
}

function attrsHeavy(elements: number, attrsPerElement: number): string {
  let out = `<root>`;
  for (let index = 0; index < elements; index++) {
    let attributes = "";
    for (let attr = 0; attr < attrsPerElement; attr++)
      attributes += ` a${attr}="value-${index}-${attr}"`;
    out += `<node${attributes}>text-${index}</node>`;
  }
  return out + `</root>`;
}

function deepNesting(levels: number, padLength: number): string {
  const pad = "padding-text ".repeat(Math.ceil(padLength / 13)).slice(0, padLength);
  let inner = `leaf-${pad}`;
  for (let depth = 0; depth < levels; depth++)
    inner = `<level${depth} id="${depth}">${pad}${inner}</level${depth}>`;
  return `<?xml version="1.0"?><root>${inner}</root>`;
}

function cdataHeavy(sections: number, sectionLength: number): string {
  const payload = "x <>&'\" ".repeat(Math.ceil(sectionLength / 8)).slice(0, sectionLength);
  let out = `<root>`;
  for (let index = 0; index < sections; index++)
    out += `<entry id="${index}"><![CDATA[${payload}]]></entry>`;
  return out + `</root>`;
}

/** Named fixtures, written locally as `test/fixtures/generated/<name>.xml`. */
export const FIXTURES: Record<string, () => string> = {
  "tiny-1k": () => rssFeed(5, 60),
  "rss-100k": () => rssFeed(300, 200),
  "attrs-heavy-100k": () => attrsHeavy(1200, 8),
  "deep-nesting-100k": () => deepNesting(1200, 60),
  "cdata-heavy-100k": () => cdataHeavy(300, 250),
  "large-1mb": () => rssFeed(3000, 220),
  "large-5mb": () => rssFeed(14_000, 250),
};

/**
 * Text flavour of a matrix fixture. It decides how V8 stores the whole document: ASCII and
 * Latin-1 stay one-byte strings, while a single character above U+00FF (poison, cjk) makes
 * the entire document two-byte (research/SYNTHESIS.md #16).
 */
export type Encoding = "ascii" | "latin1" | "poison" | "cjk";

const WORDS: Record<Exclude<Encoding, "poison">, readonly string[]> = {
  ascii: [
    "lorem",
    "ipsum",
    "dolor",
    "sit",
    "amet",
    "consectetur",
    "adipiscing",
    "elit",
    "sed",
    "do",
  ],
  latin1: ["café", "über", "straße", "niño", "garçon", "déjà", "façade", "smörgås", "crème", "año"],
  cjk: ["这是", "一个", "用于", "测试", "的", "中文", "句子", "解析器", "性能", "数据"],
};

/**
 * Deterministic text of about `length` characters. "poison" is ASCII except that one value in
 * ten starts with typographic quotes and an em dash, the way real feeds do.
 */
function text(encoding: Encoding, seed: number, length: number): string {
  const words = WORDS[encoding === "poison" ? "ascii" : encoding];
  let out = encoding === "poison" && seed % 10 === 0 ? "“Quoted” — " : "";
  for (let index = seed; out.length < length; index++)
    out += `${words[index % words.length] ?? ""} `;
  return out.slice(0, length).trimEnd();
}

/** Deterministic 32-hex-digit string, e.g. for ETags and base64-like blobs. */
function hex32(seed: number): string {
  return (Math.imul(seed + 1, 2_654_435_761) >>> 0).toString(16).padStart(8, "0").repeat(4);
}

/** Pretty-printed RSS 2.0 with a stylesheet PI, a comment, entities and CDATA descriptions. */
function matrixRss(encoding: Encoding, items: number, newline = "\n"): string {
  const lines = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<?xml-stylesheet type="text/xsl" href="/rss.xsl"?>`,
    `<!-- generated by src/bench-fixtures.ts -->`,
    `<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:dc="http://purl.org/dc/elements/1.1/">`,
    `  <channel>`,
    `    <title>Matrix feed</title>`,
    `    <link>https://example.com/</link>`,
    `    <description>${text(encoding, 1, 80)}</description>`,
  ];
  for (let index = 0; index < items; index++) {
    const amp = index % 3 === 0 ? " &amp; more" : "";
    lines.push(
      `    <item>`,
      `      <title>${text(encoding, index, 60)}${amp}</title>`,
      `      <link>https://example.com/posts/${index}?ref=rss&amp;id=${index}</link>`,
      `      <guid isPermaLink="false">post-${index}</guid>`,
      `      <pubDate>Mon, 01 Jan 2024 00:00:00 GMT</pubDate>`,
      `      <dc:creator>${text(encoding, index + 3, 14)}</dc:creator>`,
      `      <category>${text(encoding, index + 5, 10)}</category>`,
      `      <description><![CDATA[<p>${text(encoding, index, 300)}</p><a href="https://example.com/${index}">more</a>]]></description>`,
      `    </item>`,
    );
  }
  lines.push(`  </channel>`, `</rss>`, ``);
  return lines.join(newline);
}

/** Sitemap: one `<url>` per line, escaped `&amp;` in every URL, no attributes. */
function matrixSitemap(urls: number): string {
  let out = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;
  for (let index = 0; index < urls; index++) {
    const day = String((index % 28) + 1).padStart(2, "0");
    out += `<url><loc>https://example.com/catalog?item=${index}&amp;desc=vacation_${index}&amp;lang=en</loc><lastmod>2024-01-${day}</lastmod><changefreq>weekly</changefreq><priority>0.${index % 10}</priority></url>\n`;
  }
  return `${out}</urlset>\n`;
}

/** S3 ListObjectsV2 response: minified, no attributes, keys carry the encoding's text. */
function matrixS3(encoding: Encoding, keys: number): string {
  let out = `<?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>bucket</Name><Prefix></Prefix><KeyCount>${keys}</KeyCount><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated>`;
  for (let index = 0; index < keys; index++) {
    out += `<Contents><Key>photos/${text(encoding, index, 40)}-${index}.jpg</Key><LastModified>2024-01-01T00:00:00.000Z</LastModified><ETag>&quot;${hex32(index)}&quot;</ETag><Size>${(index * 7919) % 1_000_000}</Size><StorageClass>STANDARD</StorageClass></Contents>`;
  }
  return `${out}</ListBucketResult>`;
}

/** SVG 1.1: DOCTYPE, PI, comment, CDATA style, attribute-heavy shapes and long path data. */
function matrixSvg(groups: number): string {
  let out = `<?xml version="1.0" encoding="UTF-8"?>\n<?xml-stylesheet href="style.css" type="text/css"?>\n<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n<!-- generated by src/bench-fixtures.ts -->\n<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="800" height="600" viewBox="0 0 800 600">\n  <style><![CDATA[ .a { fill: #336699; stroke: #000; } .b > .c { opacity: 0.5; } ]]></style>\n  <defs><linearGradient id="g1" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#fff"/><stop offset="1" stop-color="#000"/></linearGradient></defs>\n`;
  for (let index = 0; index < groups; index++) {
    let d = `M ${index % 800} ${index % 600}`;
    for (let point = 0; point < 12; point++)
      d += ` L ${(index * 13 + point * 37) % 800} ${(index * 7 + point * 29) % 600}`;
    out += `  <g id="layer${index}" transform="translate(${index % 50},${index % 40})" class="b">\n    <rect x="${index % 700}" y="${index % 500}" width="40" height="20" rx="2" fill="#${hex32(index).slice(0, 6)}" stroke="#000" stroke-width="1" class="a c"/>\n    <circle cx="${index % 800}" cy="${index % 600}" r="${(index % 9) + 1}" fill="url(#g1)" opacity="0.8"/>\n    <path d="${d} Z" fill="none" stroke="#333" stroke-width="0.5" stroke-linejoin="round"/>\n    <text x="${index % 700}" y="${index % 500}" font-family="Verdana" font-size="12">Label ${index}</text>\n  </g>\n`;
  }
  return `${out}</svg>\n`;
}

/** SOAP 1.1 response: minified, four namespace prefixes, xsi:type attributes, base64 blobs. */
function matrixSoap(orders: number): string {
  let out = `<?xml version="1.0" encoding="UTF-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:m="urn:example:orders"><soap:Header><m:Auth soap:mustUnderstand="1"><m:Token>${hex32(1).repeat(32)}</m:Token></m:Auth></soap:Header><soap:Body><m:GetOrdersResponse><m:Orders>`;
  for (let index = 0; index < orders; index++) {
    out += `<m:Order id="${index}" currency="EUR"><m:Customer xsi:type="xsd:string">Customer ${index}</m:Customer><m:Total xsi:type="xsd:decimal">${(index * 1.37).toFixed(2)}</m:Total><m:Status>shipped</m:Status><m:Created xsi:type="xsd:dateTime">2024-01-01T10:00:00Z</m:Created></m:Order>`;
  }
  return `${out}</m:Orders><m:Attachment>${hex32(2).repeat(256)}</m:Attachment></m:GetOrdersResponse></soap:Body></soap:Envelope>`;
}

/** WordprocessingML body: minified, `w:` prefix on everything, depth 6, xml:space runs. */
function matrixOoxml(encoding: Encoding, paragraphs: number): string {
  let out = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><w:body>`;
  for (let index = 0; index < paragraphs; index++) {
    out += `<w:p w:rsidR="00A1B2C3" w:rsidRDefault="00A1B2C3"><w:pPr><w:pStyle w:val="Normal"/><w:spacing w:after="120"/></w:pPr><w:r><w:rPr><w:b/><w:sz w:val="24"/></w:rPr><w:t>${text(encoding, index, 20)}</w:t></w:r><w:r><w:t xml:space="preserve"> ${text(encoding, index + 1, 40)} </w:t></w:r></w:p>`;
  }
  return `${out}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/></w:sectPr></w:body></w:document>`;
}

/** Escaped HTML instead of CDATA: dense named and numeric entity references. */
function matrixEntities(entries: number): string {
  let out = `<?xml version="1.0" encoding="UTF-8"?>\n<feed>\n`;
  for (let index = 0; index < entries; index++) {
    out += `<entry><title>Tom &amp; Jerry&#8217;s &quot;best&quot; episode ${index}</title><content type="html">&lt;p&gt;${text("ascii", index, 120)} &lt;b&gt;bold&lt;/b&gt; &amp;amp; &#x2014; ${text("ascii", index + 4, 60)}&lt;/p&gt;</content></entry>\n`;
  }
  return `${out}</feed>\n`;
}

/**
 * Workload × encoding matrix for the spikes and competitor benches (see
 * research/edge-xml-workloads-fixtures.md §3). Each is about 100 KB unless named otherwise.
 */
export const MATRIX: Record<string, () => string> = {
  "rss-ascii": () => matrixRss("ascii", 150),
  "rss-latin1": () => matrixRss("latin1", 150),
  "rss-poison": () => matrixRss("poison", 150),
  "rss-cjk": () => matrixRss("cjk", 150),
  "rss-crlf": () => matrixRss("ascii", 150, "\r\n"),
  "rss-1mb-ascii": () => matrixRss("ascii", 1500),
  "rss-small": () => matrixRss("ascii", 4),
  "rss-1mb-poison": () => matrixRss("poison", 1500),
  "ooxml-ascii": () => matrixOoxml("ascii", 300),
  "ooxml-latin1": () => matrixOoxml("latin1", 300),
  "ooxml-poison": () => matrixOoxml("poison", 300),
  "ooxml-cjk": () => matrixOoxml("cjk", 300),
  "s3-ascii": () => matrixS3("ascii", 400),
  "s3-latin1": () => matrixS3("latin1", 400),
  "s3-poison": () => matrixS3("poison", 400),
  "s3-cjk": () => matrixS3("cjk", 400),
  "s3-small": () => matrixS3("ascii", 10),
  sitemap: () => matrixSitemap(600),
  svg: () => matrixSvg(250),
  soap: () => matrixSoap(400),
  entities: () => matrixEntities(350),
};

/** Size of the `many/` burst corpus. */
export const BURST_COUNT = 200;

/** One ~2KB document of the `many/` burst corpus. */
export function burstDocument(index: number): string {
  return rssFeed(8, 120).replaceAll("Bench", `Bench-${index}`);
}
